name: Build and Deploy to Github Pages
on: push
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Installing compiler
      - name: Fetching dependencies
        run: cargo fetch
      - name: Building
        run: trunk build --release
      - name: Deploying to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist